### ISSUE TITLE
Google Maps element requires API key

### ISSUE THREAD

**Issue by VikramTiwari** [googlecodelabs/polymer-webgl-visualization#7]
In step 3, Google Maps requires API key, else it throws a warning. Should be mentioned in the documentation somewhere regarding the same, and a link to get API key.

![screen shot 2016-07-10 at 7 16 12 pm](https://cloud.githubusercontent.com/assets/1330677/16718215/cbbc91d0-46d2-11e6-8fed-7f5d8dabc2a9.png)

**Comment by epoctic** [comment]
Not really sure its worth mentioning something like that in the tutorial, as it could needlessly complicate the tutorial for novice developers.

**Comment by VikramTiwari** [comment]
Totally forgot to update this issue. It was not working (no graph being shown) on my system due to other issues in code (forgot to add dependency). But this works fine even without an API key for maps.

Closing this. 👍  thanks for update.
